// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9P87OSKCpqIkSLhfeLt7s5rcB4uzVMtk',
    appId: '1:156251242970:android:b70cb7548258d6a48900e3',
    messagingSenderId: '156251242970',
    projectId: 'paddlme-be470',
    storageBucket: 'paddlme-be470.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9YygtQZ-GLrqmV6Qd6X4mgOmm4TRRsc',
    appId: '1:156251242970:ios:26c827ab1429a47d8900e3',
    messagingSenderId: '156251242970',
    projectId: 'paddlme-be470',
    storageBucket: 'paddlme-be470.firebasestorage.app',
    iosBundleId: 'com.example.waveShare',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9BAqdmmrJef_I5hfFvUnTgaPItznTQi8',
    appId: '1:156251242970:web:a3ca3a8f3c6d6f468900e3',
    messagingSenderId: '156251242970',
    projectId: 'paddlme-be470',
    authDomain: 'paddlme-be470.firebaseapp.com',
    storageBucket: 'paddlme-be470.firebasestorage.app',
    measurementId: 'G-0JJ4PY21XS',
  );

}